### ISSUE TITLE
New run command

### ISSUE THREAD

**Issue by frmadem** [prefapp/puzzle#29]
There will be really useful to have a command in puzzle with the ability to run something in a container for a particular service. 

The command syntax would be:
```bash
puzzle run <service>:<container> command
```

**Comment by frmadem** [comment]
Added in https://github.com/prefapp/puzzle/commit/45c7e5508cff42aca00f1c6e14c19f0a2a30da4a

**Comment by alambike** [comment]
The syntax in docker-compose run is 
```
docker-compose run <service> <construction> command
```
Service and construction separation with space instead of colon. 
What about pass all options after run to docker-compose? And maybe the same to other docker-compose commands:

build
config
create
down
events
help
kill
logs
pause
port
ps
pull
restart
rm
run
scale
start
stop
unpause
up
